import { EmployeeTask } from "@/lib/types/employee-task";

export const mockEmployeeTasks: EmployeeTask[] = [
  {
    id: "1",
    title: "Social Media Campaign Design",
    description: "Create visual assets for holiday marketing campaign",
    assignee: {
      id: "emp-001",
      name: "Sarah Anderson",
      department: "Marketing",
      email: "jessica.martinez@company.com",
      avatar: "/images/girl-avatar.jpg",
    },
    client: {
      id: "client-001",
      name: "Tech Corp",
    },
    dueDate: "2024-12-25",
    createdDate: "2024-12-15",
    priority: "High",
    status: "Completed",
    progress: 92,
    category: {
      id: "cat-001",
      name: "Marketing",
    },
    estimatedHours: 24,
    actualHours: 24,
    activityLog: [
      {
        id: "log-1",
        action: "Task Completed",
        timestamp: "2025-12-28T14:30:00",
        description: "Task marked as completed",
      },
      {
        id: "log-2",
        action: "Progress Updated To 90%",
        timestamp: "2025-12-26T11:15:00",
        description: "Progress updated by Sarah Anderson",
      },
      {
        id: "log-3",
        action: "Files Added",
        timestamp: "2025-12-20T16:45:00",
        description: "Campaign assets uploaded",
      },
      {
        id: "log-4",
        action: "Task Started",
        timestamp: "2025-12-15T09:00:00",
        description: "Sarah Anderson started working on this task",
      },
    ],
  },
  {
    id: "2",
    title: "Social Media Campaign Design",
    description: "Create visual assets for holiday marketing campaign",
    assignee: {
      id: "emp-001",
      name: "Sarah Anderson",
      department: "Marketing",
      email: "sarah.anderson@company.com",
      avatar: "/images/girl-avatar.jpg",
    },
    client: {
      id: "client-002",
      name: "Fashion Brand",
    },
    dueDate: "2024-12-25",
    createdDate: "2024-12-10",
    priority: "Medium",
    status: "InProgress",
    progress: 92,
    category: {
      id: "cat-001",
      name: "Marketing",
    },
    estimatedHours: 20,
    actualHours: 18,
  },
  {
    id: "3",
    title: "Social Media Campaign Design",
    description: "Create visual assets for holiday marketing campaign",
    assignee: {
      id: "emp-001",
      name: "Sarah Anderson",
      department: "Marketing",
      email: "sarah.anderson@company.com",
      avatar: "/images/girl-avatar.jpg",
    },
    dueDate: "2024-12-25",
    createdDate: "2024-12-12",
    priority: "Low",
    status: "NotStarted",
    progress: 0,
    category: {
      id: "cat-001",
      name: "Marketing",
    },
    estimatedHours: 15,
  },
  {
    id: "4",
    title: "Social Media Campaign Design",
    description: "Create visual assets for holiday marketing campaign",
    assignee: {
      id: "emp-001",
      name: "Sarah Anderson",
      department: "Marketing",
      email: "sarah.anderson@company.com",
      avatar: "/images/girl-avatar.jpg",
    },
    client: {
      id: "client-003",
      name: "Retail Plus",
    },
    dueDate: "2024-12-25",
    createdDate: "2024-12-08",
    priority: "High",
    status: "Completed",
    progress: 92,
    category: {
      id: "cat-001",
      name: "Marketing",
    },
    estimatedHours: 30,
    actualHours: 28,
  },
  {
    id: "5",
    title: "Social Media Campaign Design",
    description: "Create visual assets for holiday marketing campaign",
    assignee: {
      id: "emp-001",
      name: "Sarah Anderson",
      department: "Marketing",
      email: "sarah.anderson@company.com",
      avatar: "/images/girl-avatar.jpg",
    },
    dueDate: "2024-12-25",
    createdDate: "2024-12-05",
    priority: "High",
    status: "Completed",
    progress: 92,
    category: {
      id: "cat-001",
      name: "Marketing",
    },
    estimatedHours: 25,
    actualHours: 24,
  },
  {
    id: "6",
    title: "Social Media Campaign Design",
    description: "Create visual assets for holiday marketing campaign",
    assignee: {
      id: "emp-001",
      name: "Sarah Anderson",
      department: "Marketing",
      email: "sarah.anderson@company.com",
      avatar: "/images/girl-avatar.jpg",
    },
    client: {
      id: "client-001",
      name: "Tech Corp",
    },
    dueDate: "2024-12-25",
    createdDate: "2024-12-01",
    priority: "Medium",
    status: "InProgress",
    progress: 92,
    category: {
      id: "cat-001",
      name: "Marketing",
    },
    estimatedHours: 22,
    actualHours: 20,
  },
  {
    id: "7",
    title: "Social Media Campaign Design",
    description: "Create visual assets for holiday marketing campaign",
    assignee: {
      id: "emp-001",
      name: "Sarah Anderson",
      department: "Marketing",
      email: "sarah.anderson@company.com",
      avatar: "/images/girl-avatar.jpg",
    },
    dueDate: "2024-12-25",
    createdDate: "2024-11-28",
    priority: "Low",
    status: "NotStarted",
    progress: 0,
    category: {
      id: "cat-001",
      name: "Marketing",
    },
    estimatedHours: 18,
  },
  {
    id: "8",
    title: "Social Media Campaign Design",
    description: "Create visual assets for holiday marketing campaign",
    assignee: {
      id: "emp-001",
      name: "Sarah Anderson",
      department: "Marketing",
      email: "sarah.anderson@company.com",
      avatar: "/images/girl-avatar.jpg",
    },
    client: {
      id: "client-002",
      name: "Fashion Brand",
    },
    dueDate: "2024-12-25",
    createdDate: "2024-11-25",
    priority: "Low",
    status: "NotStarted",
    progress: 0,
    category: {
      id: "cat-001",
      name: "Marketing",
    },
    estimatedHours: 16,
  },
];

export const taskCategories = [
  "Marketing",
  "Development",
  "Design",
  "Content Creation",
  "Client Management",
  "Analytics",
];

export const taskPriorities = ["High", "Medium", "Low"];

export const taskStatuses = ["Not Started", "In Progress", "Completed"];

