import { Lead } from "../types";

export const mockLeads: Lead[] = [
  {
    id: "EMP001",
    name: "Michael Anderson",
    email: "anderson@email.com",
    source: "Website",
    status: "Active",
    agreementPeriod: {
      start: "Jul 9, 2025",
      end: "Jul 24, 2025",
    },
    marketRegion: "Europe",
    services: "Digital Marketing",
    contactInfo: "+9640000000",
    assignedTo: [
      { name: "Alice", initial: "A", color: "bg-red-500" },
      { name: "Sarah", initial: "S", color: "bg-blue-500" },
      { name: "Steve", initial: "S", color: "bg-green-500" },
      { name: "Steve", initial: "S", color: "bg-yellow-500" },
    ],
  },
  {
    id: "EMP002",
    name: "Michael Anderson",
    email: "anderson@email.com",
    source: "Website",
    status: "Active",
    agreementPeriod: {
      start: "Jul 9, 2025",
      end: "Jul 24, 2025",
    },
    marketRegion: "Europe",
    services: "Digital Marketing",
    contactInfo: "+9640000000",
    assignedTo: [
      { name: "Alice", initial: "A", color: "bg-red-500" },
      { name: "Sarah", initial: "S", color: "bg-blue-500" },
      { name: "Alice", initial: "A", color: "bg-green-500" },
      { name: "Steve", initial: "S", color: "bg-yellow-500" },
    ],
  },
  {
    id: "EMP003",
    name: "Michael Anderson",
    email: "anderson@email.com",
    source: "Social Media",
    status: "Active",
    agreementPeriod: {
      start: "Jul 9, 2025",
      end: "Jul 24, 2025",
    },
    marketRegion: "Europe",
    services: "Digital Marketing",
    contactInfo: "+9640000000",
    assignedTo: [
      { name: "Alice", initial: "A", color: "bg-red-500" },
      { name: "Sarah", initial: "S", color: "bg-blue-500" },
      { name: "Steve", initial: "S", color: "bg-green-500" },
      { name: "Steve", initial: "S", color: "bg-yellow-500" },
    ],
  },
  {
    id: "EMP004",
    name: "Michael Anderson",
    email: "anderson@email.com",
    source: "Referral",
    status: "Active",
    agreementPeriod: {
      start: "Jul 9, 2025",
      end: "Jul 24, 2025",
    },
    marketRegion: "Europe",
    services: "Digital Marketing",
    contactInfo: "+9640000000",
    assignedTo: [
      { name: "Alice", initial: "A", color: "bg-red-500" },
      { name: "Sarah", initial: "S", color: "bg-blue-500" },
      { name: "Steve", initial: "S", color: "bg-green-500" },

      { name: "Steve", initial: "S", color: "bg-yellow-500" },
    ],
  },
  {
    id: "EMP005",
    name: "Michael Anderson",
    email: "anderson@email.com",
    source: "Website",
    status: "Active",
    agreementPeriod: {
      start: "Jul 9, 2025",
      end: "Jul 24, 2025",
    },
    marketRegion: "Europe",
    services: "Digital Marketing",
    contactInfo: "+9640000000",
    assignedTo: [
      { name: "Alice", initial: "A", color: "bg-red-500" },
      { name: "Sarah", initial: "S", color: "bg-blue-500" },
      { name: "Steve", initial: "S", color: "bg-green-500" },
      { name: "Steve", initial: "S", color: "bg-yellow-500" },
    ],
  },
  {
    id: "EMP006",
    name: "Michael Anderson",
    email: "anderson@email.com",
    source: "Campaign",
    status: "Active",
    agreementPeriod: {
      start: "Jul 9, 2025",
      end: "Jul 24, 2025",
    },
    marketRegion: "Europe",
    services: "Digital Marketing",
    contactInfo: "+9640000000",
    assignedTo: [
      { name: "Alice", initial: "A", color: "bg-red-500" },
      { name: "Sarah", initial: "S", color: "bg-blue-500" },
      { name: "Steve", initial: "S", color: "bg-green-500" },
      { name: "Steve", initial: "S", color: "bg-yellow-500" },
    ],
  },
  {
    id: "EMP007",
    name: "Michael Anderson",
    email: "anderson@email.com",
    source: "Social Media",
    status: "Active",
    agreementPeriod: {
      start: "Jul 9, 2025",
      end: "Jul 24, 2025",
    },
    marketRegion: "Europe",
    services: "Digital Marketing",
    contactInfo: "+9640000000",
    assignedTo: [
      { name: "Alice", initial: "A", color: "bg-red-500" },
      { name: "Sarah", initial: "S", color: "bg-blue-500" },
      { name: "Steve", initial: "S", color: "bg-green-500" },
      { name: "Steve", initial: "S", color: "bg-yellow-500" },
    ],
  },
  {
    id: "EMP008",
    name: "Michael Anderson",
    email: "anderson@email.com",
    source: "Social Media",
    status: "Active",
    agreementPeriod: {
      start: "Jul 9, 2025",
      end: "Jul 24, 2025",
    },
    marketRegion: "Europe",
    services: "Digital Marketing",
    contactInfo: "+9640000000",
    assignedTo: [
      { name: "Alice", initial: "A", color: "bg-red-500" },
      { name: "Sarah", initial: "S", color: "bg-blue-500" },
      { name: "Steve", initial: "S", color: "bg-green-500" },
      { name: "Steve", initial: "S", color: "bg-yellow-500" },
    ],
  },
  {
    id: "EMP009",
    name: "Michael Anderson",
    email: "anderson@email.com",
    source: "Social Media",
    status: "Active",
    agreementPeriod: {
      start: "Jul 9, 2025",
      end: "Jul 24, 2025",
    },
    marketRegion: "Europe",
    services: "Digital Marketing",
    contactInfo: "+9640000000",
    assignedTo: [
      { name: "Alice", initial: "A", color: "bg-red-500" },
      { name: "Sarah", initial: "S", color: "bg-blue-500" },
      { name: "Steve", initial: "S", color: "bg-green-500" },
      { name: "Steve", initial: "S", color: "bg-yellow-500" },
    ],
  },
  {
    id: "EMP010",
    name: "Michael Anderson",
    email: "anderson@email.com",
    source: "Social Media",
    status: "Active",
    agreementPeriod: {
      start: "Jul 9, 2025",
      end: "Jul 24, 2025",
    },
    marketRegion: "Europe",
    services: "Digital Marketing",
    contactInfo: "+9640000000",
    assignedTo: [
      { name: "Alice", initial: "A", color: "bg-red-500" },
      { name: "Sarah", initial: "S", color: "bg-blue-500" },
      { name: "Steve", initial: "S", color: "bg-green-500" },
      { name: "Steve", initial: "S", color: "bg-yellow-500" },
    ],
  },
];
